export enum JobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PARSED = 'PARSED',
  VALIDATED = 'VALIDATED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  LOADING = 'LOADING',
  DONE = 'DONE',
  FAILED = 'FAILED',
}
